version: 1
formatters:
  simple:
    format: "[%(asctime)s] %(levelname)s - %(message)s"
handlers:
  file:
    class: logging.FileHandler
    filename: logs/pipeline.log
    formatter: simple
    level: INFO
root:
  level: INFO
  handlers: [file]
